baseurl: "http://nostalgix.org"
exclude: ['Rakefile', 'README.markdown', 'Gemfile', 'Gemfile.lock']
#markdown: maruku
markdown: kramdown
#markdown: rdiscount
highlighter: pygments
github_username: madhatter
