#baseurl: "http://nostalgix.org"
exclude: ['Rakefile', 'README.markdown', 'Gemfile', 'Gemfile.lock']
#markdown: maruku
markdown: kramdown
#markdown: rdiscount
highlighter: rouge
github_username: madhatter
plugins: 
  - 'jekyll-sitemap'
